### ISSUE TITLE
RFM69 getting stuck in frequency synthesizer mode causes random code freezes

### ISSUE THREAD

**Issue by Tsarcasm** [LowPowerLab/RFM69#162]
Note: this is a hardware issue, not a problem with this library, but changes can be made to the library to mitigate the problem. These issues occur when using the RadioHead library too. 

I've been experiencing persistent random freezes when transmitting, with no obvious explanation. These freezes occur anywhere from a couple minutes to several hours from start-up. Resetting the board restarts communication, only for another freeze to occur some time later.

After some painful debugging, I found that `sendFrame` will occasionally hang when waiting for the `PACKETSENT` flag to be set in `REG_IRQFLAGS2`, after the opmode is set to TX. 
We get stuck in this loop: https://github.com/LowPowerLab/RFM69/blob/adc94d2d2b61b44b33e769715edce663464b71c9/RFM69.cpp#L348

Examining the registers on these hangs shows that the radio is failing to exit Frequency Synthesizer mode. I'm not exactly sure what causes this but these guys have encountered the same problem and reckon it's due to the PLL circuit failing to lock.
https://hackaday.io/project/9064-andxor-defcon-24-badge/log/40875-adventures-with-the-rfm69

Switching the radio back to standby mode forces it to stop waiting for the PLL lock, and this solves the problem. Subsequent transmissions will work as expected. We don't need to restart the chip or cycle the power.

My quick fix was to add a timeout of 100ms to the problematic while loop. 
`while ((readReg(REG_IRQFLAGS2) & RF_IRQFLAGS2_PACKETSENT) == 0x00)` 
If the chip gets stuck in FS mode, we bail from the loop and the following line resets to standby mode.
The datasheet specifies FS mode should only last about 60 microseconds, so 100ms is ample time. Lower timeouts are probably desirable but I haven't tested with anything lower than 100ms. I would expect a timeout of a couple ms would be sufficient. 

I've tested this fix over 72 hours. The radio got stuck in FS mode 43 times, resetting to standby mode after the timeout resulted in error-free transmission immediately afterwards.

If you want, I can fork the repo and make a PR with these changes. I'm going to test performance when reducing the timeout time over the next few days.

----------------------------

It appears as if several people have reported similar issues but have been unable to describe it. The descriptions of these issues seem very familiar.  
https://lowpowerlab.com/forum/rf-range-antennas-rfm69-library/random-receive-failhang-rfm69hcw/
https://blog.devmobile.co.nz/2019/07/21/rfm69-hat-library-receive-lockup-debugging/
https://forum.mysensors.org/topic/3881/rfm69-moteino-serial-gateway-freezes/7?lang=en-GB

It also seems like this only affects some RFM69 chips, but I've had this occur on multiple chips. I could just be unlucky and have a bad batch. I don't seem to have an issue with misplaced capacitors like the team in the Hackaday article, but it could well be poor soldering or part placement on the radios I haven't been able to spot.

I'm running on an stm32f103, but I've experienced these problems on atmega328 boards too.

**Comment by LowPowerLab** [comment]
@Tsarcasm Thanks for the detailed description.

The HAD post talks about a dislodged PLL capacitor. That is broken hardware. As soon as the capacitor was replaced the problem went away. The LPL post talks about a Sparkfun RFM69 breakout + breadboard, a recipe for failure. It's a don't care to me. The others are also $1 arduino minis loosely wired to RFM69, I hear of such combination fails all the time, also don't cares. I never hear about Moteinos and boards I design and make failing.

So I have to say reports of freezes were never really conclusive to point to library problems, or hardware properly designed.
We have many systems some with many nodes running in various places and environments, for years without being touched, some of critical importance, they never freeze or we'd hear about it. If this was randomly happening, we'd see batteries draining to brownout, and other bad things happen, it would be pretty obvious. I have to say all these nodes are made by LowPowerLab, made in USA, rigorously inspected and tested, usually packed and delivered carefully. This is what we can support and warrant, not unknown boards, DIY and other experimental things on breadboards that people do and then fail.

You mention STM32, I wonder if SPI clocking has any role in this. It can't be over 10mhz per datasheet. How the RFM69 is wired is also important, I've seen many failures because people don't give importance to that aspect and think mhz can travel well over breadboards and floating wires.

If you can provide a way to replicate this on a LowPowerLab board, I would be interested in knowing and trying it out, and I will reopen the issue.
